### ISSUE TITLE
Reply to the email

### ISSUE THREAD

**Issue by kaisugi** [sreehari32/blog#1]
Hi, I'm the author of the HugoTeX theme. I read your email. Thanks for using my theme!

I'm not 100% sure, but the issue in your repository may be caused by static directory settings.
Hugo accepts `/static` as the directory of static files. You specify the different name `/assets`. Therefore Hugo cannot recognize it
Please look at the following link
https://gohugo.io/content-management/static-files/

**Comment by kaisugi** [comment]
I confirmed that the image is displayed when using `/static`
https://kaisugi.github.io/debug-hugo-theme/img1.png

**Comment by sreehari32** [comment]
hi sir, thanks for your time ,
But the problem remains unsolved
pls see my [hugo.toml](https://github.com/sreehari32/blog/blob/main/hugo.toml) file. Its the same as you have given. 

i renamed the image to accuracy_1.png and moved to static folder:-    Result >> image not displayed


i tried multiple image paths [trial and error]
<img width="321" alt="image" src="https://github.com/sreehari32/blog/assets/51872549/ec9c53fe-a97a-4b59-adf1-b2eb65adb2ba">

but when blog is hosted it looks like this 
<img width="288" alt="image" src="https://github.com/sreehari32/blog/assets/51872549/6178dec9-b18d-4265-896e-252c61505f5a">

**Comment by sreehari32** [comment]
if you can tell me where i can see the hugo created html code, may be we can change the file path accordingly.

**Comment by kaisugi** [comment]
Please try this:

`<img src="../../accuracy_1.png" alt="alt text">`

**Comment by sreehari32** [comment]
Thank you sir, this worked... Thanks a lot for the help.. 


I would like to know the details of who all visit my page, like how many people visited in a day etc.  Is there a way to do that.?

**Comment by kaisugi** [comment]
You can use external tools such as Google Analytics.
You could implement web counters or something by yourself, but I don't recommend it.
The best practice in the web development is to stand on the giant shoulders (use external tools as possible) 😃

**Comment by sreehari32** [comment]
Hi,
Thank your sir for your guidance. I will read about incorporating google
analytics and get back to you.
Sincerely
Sreehari
